# Generated by Django 6.0.7 on 2026-09-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_prefix', models.CharField(blank=True, default='STU', max_length=30)),
                ('student_separator', models.CharField(blank=True, default='-', max_length=5)),
                ('student_digits', models.PositiveIntegerField(default=4)),
                ('student_include_year', models.BooleanField(default=False)),
                ('student_year_digits', models.PositiveIntegerField(default=4)),
                ('student_start_number', models.PositiveIntegerField(default=1)),
                ('employee_prefix', models.CharField(blank=True, default='EMP', max_length=30)),
                ('employee_separator', models.CharField(blank=True, default='-', max_length=5)),
                ('employee_digits', models.PositiveIntegerField(default=4)),
                ('employee_include_year', models.BooleanField(default=False)),
                ('employee_year_digits', models.PositiveIntegerField(default=4)),
                ('employee_start_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Number Settings',
                'verbose_name_plural': 'School Number Settings',
            },
        ),
    ]
