# Generated by Django 6.0.7 on 2026-08-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_double_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='is_fixed',
            field=models.BooleanField(default=False),
        ),
    ]
