# Generated by Django 6.0.7 on 2026-08-22 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0001_initial'),
        ('scheduling', '0002_timetableentry_is_double_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduling_teacher', to='hr_payroll.employee'),
        ),
    ]
