# Generated by Django 6.0.7 on 2026-09-10 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_teacher_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='scheduling.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='scheduling.teacher')),
            ],
            options={
                'ordering': ['teacher__name', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject'), name='unique_teacher_subject_assignment')],
            },
        ),
    ]
