# Generated by Django 6.0.7 on 2026-09-10 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_teachersubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='scheduling.teacher')),
            ],
            options={
                'ordering': ['teacher__name', 'class_name', 'stream'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'class_name', 'stream'), name='unique_teacher_class_assignment')],
            },
        ),
        migrations.CreateModel(
            name='TeacherTeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_class_assignments', to='scheduling.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='scheduling.teacher')),
            ],
            options={
                'ordering': ['teacher__name', 'class_name', 'stream', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject', 'class_name', 'stream'), name='unique_teacher_teaching_assignment')],
            },
        ),
    ]
