# Generated by Django 6.0.7 on 2026-09-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_teacherclassassignment_teacherteachingassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherteachingassignment',
            name='lessons_per_week',
            field=models.PositiveIntegerField(default=1, help_text='Number of lessons this teacher should teach this subject to this class each week.'),
        ),
    ]
