# Generated by Django 6.0.7 on 2026-09-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_teacherteachingassignment_lessons_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this timetable entry is visible to portal users.'),
        ),
    ]
