# Generated by Django 6.0.7 on 2026-09-15 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_timetableversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='scheduling.timetableversion'),
        ),
    ]
