# Generated by Django 6.0.7 on 2026-09-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_timetableentry_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableAssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('lessons_per_week', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(choices=[('SEPARATE', 'Separate Class'), ('JOINT', 'Joint Lesson')], default='SEPARATE', max_length=20)),
                ('duration', models.CharField(choices=[('SINGLE', 'Single Lesson'), ('DOUBLE', 'Double Lesson')], default='SINGLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_name', 'stream', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableAssignmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='scheduling.timetableassignmentgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_assignment_members', to='scheduling.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_assignment_members', to='scheduling.teacher')),
            ],
            options={
                'ordering': ['subject__name', 'teacher__name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'teacher', 'subject'), name='unique_timetable_assignment_member')],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('LESSON', 'Lesson'), ('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('GAMES', 'Games'), ('ACTIVITY', 'Activity')], default='LESSON', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slot_rules', to='scheduling.day')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slot_rules', to='scheduling.period')),
            ],
            options={
                'ordering': ['day__order', 'period__order'],
                'constraints': [models.UniqueConstraint(fields=('day', 'period'), name='unique_timetable_slot_rule')],
            },
        ),
    ]
