# Generated by Django 6.0.7 on 2026-09-16 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_feepayment_receipt_number'),
        ('scheduling', '0010_timetableassignmentgroup_timetableassignmentmember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_configurations', to='fees.academicyear')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_configurations', to='fees.term')),
            ],
            options={
                'ordering': ['-academic_year__year', 'term__order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TimetableConfiguredSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField(default=1)),
                ('period_name', models.CharField(default='Period 1', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('LESSON', 'Lesson'), ('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('GAMES', 'Games'), ('ACTIVITY', 'Activity'), ('ASSEMBLY', 'Assembly')], default='LESSON', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scheduling.timetableconfiguration')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_timetable_slots', to='scheduling.day')),
            ],
            options={
                'ordering': ['day__order', 'period_number', 'start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='timetableconfiguration',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term'), name='unique_timetable_configuration_year_term'),
        ),
        migrations.AddConstraint(
            model_name='timetableconfiguredslot',
            constraint=models.UniqueConstraint(fields=('configuration', 'day', 'period_number'), name='unique_configured_timetable_slot'),
        ),
    ]
