# Generated by Django 6.0.7 on 2026-09-18 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0011_timetableconfiguration_timetableconfiguredslot_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetableconfiguredslot',
            options={'ordering': ['period_number', 'start_time']},
        ),
        migrations.RemoveConstraint(
            model_name='timetableconfiguredslot',
            name='unique_configured_timetable_slot',
        ),
        migrations.AddField(
            model_name='timetableassignmentgroup',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_groups', to='scheduling.timetableconfiguration'),
        ),
        migrations.AddConstraint(
            model_name='timetableconfiguredslot',
            constraint=models.UniqueConstraint(fields=('configuration', 'period_number'), name='unique_configured_timetable_slot'),
        ),
        migrations.RemoveField(
            model_name='timetableconfiguredslot',
            name='day',
        ),
    ]
