# Generated by Django 6.0.7 on 2026-08-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('class_name', models.CharField(max_length=30)),
                ('stream', models.CharField(max_length=20)),
                ('parent_name', models.CharField(max_length=150)),
                ('parent_phone', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('date_admitted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
