# Generated by Django 6.0.7 on 2026-09-18 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_admission_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_no', models.CharField(blank=True, max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('requested_class', models.CharField(max_length=30)),
                ('requested_stream', models.CharField(blank=True, max_length=20)),
                ('parent_name', models.CharField(max_length=150)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Admitted', 'Admitted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('admitted_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_application', to='students.student')),
            ],
        ),
    ]
