# Generated by Django 6.0.7 on 2026-09-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_onlineapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='onlineapplication',
            name='status_reference',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
