# Generated by Django 6.0.7 on 2026-09-18 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0004_alter_feepayment_receipt_number'),
        ('students', '0004_onlineapplication_status_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_class', models.CharField(max_length=100)),
                ('previous_stream', models.CharField(blank=True, max_length=100)),
                ('promoted_class', models.CharField(max_length=100)),
                ('promoted_stream', models.CharField(blank=True, max_length=100)),
                ('promoted_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_promotions', to='fees.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_history', to='students.student')),
            ],
            options={
                'ordering': ['-promoted_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_promotion_year')],
            },
        ),
    ]
