# Generated by Django 6.0.7 on 2026-09-11 15:18

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductiontype',
            name='calculation_base',
            field=models.CharField(choices=[('BASIC', 'Basic Salary'), ('GROSS', 'Gross Salary'), ('TAXABLE', 'Taxable Income')], default='BASIC', max_length=20),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='calculation_method',
            field=models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='effective_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='is_compulsory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='maximum_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='deductiontype',
            name='minimum_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
