# Generated by Django 6.0.7 on 2026-09-11 15:35

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0002_deductiontype_calculation_base_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSSFRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lower_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('employee_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('employee_cap', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['lower_limit'],
            },
        ),
        migrations.CreateModel(
            name='PAYERelief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PAYETaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lower_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=7)),
                ('effective_from', models.DateField(default=django.utils.timezone.localdate)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['lower_limit'],
            },
        ),
    ]
