# Generated by Django 6.0.7 on 2026-09-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionaldocument',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaldocument',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
