# Generated by Django 6.0.7 on 2026-08-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0002_academic_year_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='old_academic_year',
            field=models.CharField(blank=True, default='2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='old_term',
            field=models.CharField(blank=True, default='1', max_length=20),
        ),
    ]
