# Generated by Django 6.0.7 on 2026-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_alter_feerecord_old_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_number',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
