# Generated by Django 6.0.7 on 2026-09-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0005_feestructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
