# Generated by Django 6.0.7 on 2026-09-18 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0006_term_closed_at_term_end_date_term_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='fees.academicyear'),
        ),
    ]
