# Generated by Django 6.0.7 on 2026-09-19 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0007_term_academic_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_role', models.CharField(choices=[('ADMIN', 'Admin'), ('PARENT', 'Parent'), ('STUDENT', 'Student')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank'), ('OTHER', 'Other')], default='MPESA', max_length=30)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REVERSED', 'Reversed')], db_index=True, default='INITIATED', max_length=20)),
                ('merchant_request_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('checkout_request_id', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('account_reference', models.CharField(blank=True, default='', max_length=100)),
                ('provider_response_code', models.CharField(blank=True, default='', max_length=50)),
                ('provider_response_description', models.TextField(blank=True, default='')),
                ('provider_receipt', models.CharField(blank=True, default='', max_length=100)),
                ('provider_raw_response', models.JSONField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_transaction', to='fees.feepayment')),
                ('fee_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payments', to='fees.feerecord')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_fee_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='fees_online_status_21e961_idx'), models.Index(fields=['payer', '-created_at'], name='fees_online_payer_i_af371f_idx'), models.Index(fields=['fee_record', '-created_at'], name='fees_online_fee_rec_2bd1db_idx')],
            },
        ),
    ]
