# Generated by Django 6.0.7 on 2026-09-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_onlinepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal code, e.g. MPESA, BANK', max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='MPESA', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('online_enabled', models.BooleanField(default=True)),
                ('available_to_parents', models.BooleanField(default=True)),
                ('available_to_students', models.BooleanField(default=True)),
                ('available_to_admin', models.BooleanField(default=True)),
                ('automatic_verification', models.BooleanField(default=False, help_text='Automatically verify provider transactions.')),
                ('mpesa_paybill', models.CharField(blank=True, default='', max_length=50)),
                ('mpesa_till', models.CharField(blank=True, default='', max_length=50)),
                ('mpesa_shortcode', models.CharField(blank=True, default='', max_length=50)),
                ('mpesa_account_reference', models.CharField(blank=True, default='', max_length=100)),
                ('bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=100)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=150)),
                ('instructions', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
