# Generated by Django 6.0.7 on 2026-09-19 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0009_paymentmethod'),
        ('students', '0006_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternatePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('paybill', 'M-Pesa PayBill'), ('till', 'M-Pesa Till'), ('bank', 'Bank Payment')], max_length=20)),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('external_reference', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternate_payments', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
