# Generated by Django 6.0.7 on 2026-09-19 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_alternatepayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternatePaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paybill_number', models.CharField(blank=True, default='', max_length=50)),
                ('paybill_instructions', models.TextField(blank=True, default="Use the learner's admission number as the account/reference.")),
                ('till_number', models.CharField(blank=True, default='', max_length=50)),
                ('till_instructions', models.TextField(blank=True, default='Keep the M-Pesa transaction message for verification.')),
                ('bank_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=150)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=100)),
                ('bank_branch', models.CharField(blank=True, default='', max_length=150)),
                ('bank_instructions', models.TextField(blank=True, default="Use the learner's admission number as the payment reference.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alternate Payment Settings',
                'verbose_name_plural': 'Alternate Payment Settings',
            },
        ),
    ]
