# Generated by Django 6.0.7 on 2026-09-19 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0011_alternatepaymentsettings'),
        ('students', '0006_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TillPaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone_number', models.CharField(max_length=30)),
                ('till_number', models.CharField(default='7642636', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired'), ('UNMATCHED', 'Unmatched'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_time', models.CharField(blank=True, default='', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='till_payment_intents', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'amount', 'status'], name='fees_tillpa_phone_n_12c467_idx'), models.Index(fields=['transaction_id'], name='fees_tillpa_transac_8c5c72_idx')],
            },
        ),
    ]
