# Generated by Django 6.0.7 on 2026-09-20 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0012_tillpaymentintent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tillpaymentintent',
            name='online_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='till_payment_intent', to='fees.onlinepayment'),
        ),
    ]
