# Generated by Django 6.0.7 on 2026-09-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0013_tillpaymentintent_online_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomaticPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('mpesa_online_enabled', models.BooleanField(default=True)),
                ('mpesa_online_shortcode', models.CharField(blank=True, default='', max_length=50)),
                ('mpesa_online_consumer_key', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_online_consumer_secret', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_online_passkey', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_online_callback_url', models.URLField(blank=True, default='')),
                ('mpesa_online_account_reference', models.CharField(blank=True, default='SCHOOLFEES', max_length=100)),
                ('mpesa_till_enabled', models.BooleanField(default=True)),
                ('mpesa_till_number', models.CharField(blank=True, default='', max_length=50)),
                ('mpesa_till_shortcode', models.CharField(blank=True, default='', max_length=50)),
                ('mpesa_till_consumer_key', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_till_consumer_secret', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_till_passkey', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_till_callback_url', models.URLField(blank=True, default='')),
                ('mpesa_paybill_enabled', models.BooleanField(default=True)),
                ('mpesa_paybill_number', models.CharField(blank=True, default='', max_length=50)),
                ('mpesa_paybill_account', models.CharField(blank=True, default='', max_length=100)),
                ('mpesa_paybill_shortcode', models.CharField(blank=True, default='', max_length=50)),
                ('mpesa_paybill_consumer_key', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_paybill_consumer_secret', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_paybill_passkey', models.CharField(blank=True, default='', max_length=255)),
                ('mpesa_paybill_validation_url', models.URLField(blank=True, default='')),
                ('mpesa_paybill_confirmation_url', models.URLField(blank=True, default='')),
                ('bank_enabled', models.BooleanField(default=True)),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=100)),
                ('bank_account_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_api_url', models.URLField(blank=True, default='')),
                ('bank_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('bank_client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Automatic Payment Settings',
                'verbose_name_plural': 'Automatic Payment Settings',
            },
        ),
    ]
