# Generated by Django 6.0.7 on 2026-09-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0014_automaticpaymentsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_access_token_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_account_type',
            field=models.CharField(blank=True, default='Business', max_length=50),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_account_validation_endpoint',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_authentication_method',
            field=models.CharField(blank=True, default='OAuth2', max_length=100),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_auto_receipt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_auto_reconciliation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_balance_endpoint',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_branch_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_currency',
            field=models.CharField(blank=True, default='KES', max_length=20),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_duplicate_protection',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_last_transaction_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_manual_reference',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_maximum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_minimum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_polling_interval',
            field=models.PositiveIntegerField(default=5, help_text='Polling interval in minutes.'),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_reference_mode',
            field=models.CharField(choices=[('ADMISSION', 'Student Admission Number'), ('MANUAL', 'Manual Reference'), ('ACCOUNT', 'Configured Account/Reference')], default='ADMISSION', max_length=50),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_reference_prefix',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_statement_endpoint',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_swift_bic',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_transaction_endpoint',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_transaction_polling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_verification_status',
            field=models.CharField(blank=True, default='NOT_CONFIGURED', max_length=50),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_webhook_secret',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='automaticpaymentsettings',
            name='bank_webhook_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
