# Generated by Django 6.0.7 on 2026-09-20 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0015_automaticpaymentsettings_bank_access_token_url_and_more'),
        ('students', '0006_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, default='', max_length=200)),
                ('bank_account_number', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('reference', models.CharField(blank=True, db_index=True, default='', max_length=300)),
                ('payer_name', models.CharField(blank=True, default='', max_length=300)),
                ('payer_account', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=20)),
                ('transaction_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('UNMATCHED', 'Unmatched'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('ERROR', 'Verification Error')], db_index=True, default='PENDING', max_length=30)),
                ('verification_message', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction', to='fees.feepayment')),
                ('fee_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='fees.feerecord')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_transactions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
