# Generated by Django 6.0.7 on 2026-09-20 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0016_banktransaction'),
        ('students', '0006_student_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPaybillTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('transaction_time', models.CharField(blank=True, max_length=100)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('business_short_code', models.CharField(blank=True, max_length=50)),
                ('bill_ref_number', models.CharField(blank=True, db_index=True, max_length=150)),
                ('invoice_number', models.CharField(blank=True, max_length=150)),
                ('org_account_balance', models.CharField(blank=True, max_length=100)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=150)),
                ('msisdn', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VALIDATED', 'Validated'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('DUPLICATE', 'Duplicate'), ('ERROR', 'Error')], db_index=True, default='RECEIVED', max_length=30)),
                ('validation_response', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('verification_message', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_paybill_transaction', to='fees.feepayment')),
                ('fee_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_paybill_transactions', to='fees.feerecord')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_paybill_transactions', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bill_ref_number', 'status'], name='fees_mpesap_bill_re_ca6e2d_idx'), models.Index(fields=['status', 'created_at'], name='fees_mpesap_status_cb0e4d_idx')],
            },
        ),
    ]
