# Generated by Django 6.0.7 on 2026-08-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_department_description_alter_role_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Luhan School', max_length=200)),
                ('motto', models.CharField(blank=True, default='', max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_branding/')),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('alternative_phone', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('physical_address', models.CharField(blank=True, default='', max_length=300)),
                ('postal_address', models.CharField(blank=True, default='', max_length=300)),
                ('school_code', models.CharField(blank=True, default='', max_length=100)),
                ('additional_information', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School Branding',
                'verbose_name_plural': 'School Branding',
            },
        ),
    ]
