# Generated by Django 6.0.7 on 2026-09-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='Africa/Nairobi', help_text="User's preferred IANA timezone, e.g. Africa/Nairobi or Europe/London.", max_length=64),
        ),
    ]
