# Generated by Django 6.0.7 on 2026-08-09 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0003_alter_feerecord_old_academic_year_and_more'),
        ('students', '0002_alter_student_admission_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment', models.CharField(choices=[('OPENER', 'Opener Assessment'), ('MIDTERM', 'Mid-Term Assessment'), ('ENDTERM', 'End-Term Assessment'), ('ENDYEAR', 'End-Year Assessment')], max_length=20)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('out_of', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='fees.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='fees.term')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_records', to='academic.subject')),
            ],
            options={
                'ordering': ['student', 'subject', 'academic_year', 'term', 'assessment'],
                'unique_together': {('student', 'subject', 'academic_year', 'term', 'assessment')},
            },
        ),
    ]
