# Generated by Django 6.0.7 on 2026-08-09 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('fees', '0003_alter_feerecord_old_academic_year_and_more'),
        ('students', '0002_alter_student_admission_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('teacher_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_results', to='fees.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academic.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_results', to='fees.term')),
            ],
            options={
                'ordering': ['student', 'subject'],
            },
        ),
        migrations.DeleteModel(
            name='AcademicRecord',
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'term', 'subject'), name='unique_student_term_subject'),
        ),
    ]
