# Generated by Django 6.0.7 on 2026-08-10 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_subject_code_alter_subject_name_assessment_and_more'),
        ('fees', '0003_alter_feerecord_old_academic_year_and_more'),
        ('students', '0002_alter_student_admission_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['student', 'subject', 'assessment_type']},
        ),
        migrations.RemoveConstraint(
            model_name='assessment',
            name='unique_student_term_subject',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academic.assessmenttype'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'term', 'subject', 'assessment_type'), name='unique_student_term_subject_assessment'),
        ),
    ]
