# Generated by Django 6.0.7 on 2026-08-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='code',
            field=models.CharField(default='STREAM', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
