# Generated by Django 6.0.7 on 2026-09-18 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_gradingscale'),
        ('fees', '0007_term_academic_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField()),
                ('warning_minutes', models.PositiveIntegerField(default=1440)),
                ('is_reopened', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_windows', to='fees.academicyear')),
                ('assessment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_windows', to='academic.assessmenttype')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_windows', to='fees.term')),
            ],
            options={
                'ordering': ['-deadline'],
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'term', 'assessment_type'), name='unique_assessment_window')],
            },
        ),
    ]
