# Generated by Django 6.0.7 on 2026-09-26 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_assessmentwindow'),
        ('fees', '0019_reset_feepayment_sequence'),
        ('students', '0009_reset_parent_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['academic_year', 'term', 'week_number'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='assessment',
            name='unique_student_term_subject_assessment',
        ),
        migrations.AddField(
            model_name='assessmentweek',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_weeks', to='fees.academicyear'),
        ),
        migrations.AddField(
            model_name='assessmentweek',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_weeks', to='fees.term'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academic.assessmentweek'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year', 'term', 'subject', 'assessment_week', 'assessment_type'), name='unique_student_term_week_subject_assessment'),
        ),
        migrations.AddConstraint(
            model_name='assessmentweek',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term', 'week_number'), name='unique_assessment_week'),
        ),
    ]
