import os
from dotenv import load_dotenv
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.
"""

from pathlib import Path


# =========================================================
# BASE DIRECTORY
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# =========================================================
# SECURITY
# =========================================================

DEBUG = os.environ.get("DEBUG", "True").strip().lower() in ("1", "true", "yes", "on")

SECRET_KEY = os.environ.get("SECRET_KEY", "").strip()

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only-insecure-key"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY environment variable is required when DEBUG=False."
        )

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        "ALLOWED_HOSTS",
        "127.0.0.1,localhost",
    ).split(",")
    if h.strip()
]

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "CSRF_TRUSTED_ORIGINS",
        "",
    ).split(",")
    if origin.strip()
]


# =========================================================
# APPLICATIONS
# =========================================================

INSTALLED_APPS = [
    "termly_submission",
    'weekly_reports',
    "number_formats",

    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Crispy Forms
    'crispy_forms',
    'crispy_bootstrap5',

    # Luhan ERP apps
    'accounts',
    'dashboard',
    'students',
    'academic',
    'parents',
    'fees',
    'timetable',
    "hr_payroll",
    "attendance",
    "transport",
    "hostel",
    "inventory",
    "library",
    "noticeboard",
    "messaging",
    "lms",
    "professional_documents",
]


# =========================================================
# MIDDLEWARE
# =========================================================

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'timetable.middleware.TimetableLiveSyncMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.timezone_middleware.UserTimezoneMiddleware',

    'django.contrib.messages.middleware.MessageMiddleware',

    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# =========================================================
# URL CONFIGURATION
# =========================================================

ROOT_URLCONF = 'config.urls'


# =========================================================
# TEMPLATES
# =========================================================

TEMPLATES = [

    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',

        'DIRS': [
            BASE_DIR / 'templates',
        ],

        'APP_DIRS': True,

        'OPTIONS': {

            'context_processors': [

                'django.template.context_processors.request',

                'django.contrib.auth.context_processors.auth',

                'django.contrib.messages.context_processors.messages',

                'accounts.context_processors.branding.school_branding',
                'accounts.context_processors.permissions.erp_permissions',
                    'accounts.context_processors.permissions.portal_capabilities',
            ],
        },
    },
]


# =========================================================
# WSGI
# =========================================================

WSGI_APPLICATION = 'config.wsgi.application'


# =========================================================
# DATABASE
# =========================================================

DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
            "OPTIONS": {
                "timeout": 20,
            },
        }
    }


# =========================================================
# PASSWORD VALIDATION
# =========================================================

AUTH_PASSWORD_VALIDATORS = [

    {
        'NAME':
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.CommonPasswordValidator',
    },

    {
        'NAME':
        'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# =========================================================
# INTERNATIONALIZATION
# =========================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# =========================================================
# STATIC FILES
# =========================================================

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# =========================================================
# MEDIA FILES
# =========================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", str(BASE_DIR / "media")))


# =========================================================
# DEFAULT PRIMARY KEY
# =========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# =========================================================
# CRISPY FORMS
# =========================================================

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'

CRISPY_TEMPLATE_PACK = 'bootstrap5'




# ============================================================
# M-PESA DARAJA CONFIGURATION
# ============================================================

MPESA_ENVIRONMENT = os.environ.get(
    "MPESA_ENVIRONMENT",
    "sandbox",
).strip().lower()

MPESA_CONSUMER_KEY = os.environ.get(
    "MPESA_CONSUMER_KEY",
    "",
).strip()

MPESA_CONSUMER_SECRET = os.environ.get(
    "MPESA_CONSUMER_SECRET",
    "",
).strip()

MPESA_PASSKEY = os.environ.get(
    "MPESA_PASSKEY",
    "",
).strip()

MPESA_SHORTCODE = os.environ.get(
    "MPESA_SHORTCODE",
    "",
).strip()

MPESA_CALLBACK_URL = os.environ.get(
    "MPESA_CALLBACK_URL",
    "",
).strip()

MPESA_ACCOUNT_REFERENCE = os.environ.get(
    "MPESA_ACCOUNT_REFERENCE",
    "SCHOOLFEES",
).strip()

MPESA_TRANSACTION_DESC = os.environ.get(
    "MPESA_TRANSACTION_DESC",
    "School Fees Payment",
).strip()





# =========================================================
# ALTERNATE FEE PAYMENT
# Independent from the existing online STK payment system
# =========================================================
ALTERNATE_MPESA_PAYBILL = os.getenv("ALTERNATE_MPESA_PAYBILL", "")
ALTERNATE_MPESA_TILL = os.getenv("ALTERNATE_MPESA_TILL", "7642636")
ALTERNATE_BANK_NAME = os.getenv("ALTERNATE_BANK_NAME", "")
ALTERNATE_BANK_ACCOUNT = os.getenv("ALTERNATE_BANK_ACCOUNT", "")
ALTERNATE_BANK_BRANCH = os.getenv("ALTERNATE_BANK_BRANCH", "")
ALTERNATE_BANK_ACCOUNT_NAME = os.getenv("ALTERNATE_BANK_ACCOUNT_NAME", "")

# =========================================================
# PRODUCTION SECURITY
# =========================================================

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if DEBUG:
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
else:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Enable HSTS only after the production domain is confirmed.
SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

