# Generated by Django 6.0.7 on 2026-09-16 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(blank=True, max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'stream'],
            },
        ),
        migrations.CreateModel(
            name='TimetableConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('constraint_type', models.CharField(choices=[('TEACHER', 'Teacher'), ('CLASS', 'Class'), ('ROOM', 'Room'), ('SUBJECT', 'Subject'), ('DAY', 'Day'), ('PERIOD', 'Period')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('hard_constraint', models.BooleanField(default=True)),
                ('weight', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimetablePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('is_break', models.BooleanField(default=False)),
                ('is_lunch', models.BooleanField(default=False)),
                ('is_activity', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('CLASSROOM', 'Classroom'), ('LAB', 'Laboratory'), ('ICT', 'ICT / Computer Room'), ('LIBRARY', 'Library'), ('HALL', 'Hall'), ('FIELD', 'Field'), ('OTHER', 'Other')], default='CLASSROOM', max_length=30)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=50)),
                ('term_name', models.CharField(max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimetableTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('staff_number', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='timetable.timetablesubject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LessonRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_per_week', models.PositiveIntegerField(default=1)),
                ('duration_periods', models.PositiveIntegerField(default=1)),
                ('requires_double', models.BooleanField(default=False)),
                ('practical', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requirements', to='timetable.timetableclass')),
                ('preferred_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timetableday')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_requirements', to='timetable.timetableroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_requirements', to='timetable.timetablesubject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_requirements', to='timetable.timetableteacher')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_periods', models.PositiveIntegerField(default=1)),
                ('locked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_lessons', to='timetable.timetableclass')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetableday')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetableperiod')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timetableroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetablesubject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timetableteacher')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='timetable.timetableterm')),
            ],
            options={
                'ordering': ['day__order', 'period__order'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetableday')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.timetableperiod')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='timetable.timetableteacher')),
            ],
            options={
                'unique_together': {('teacher', 'day', 'period')},
            },
        ),
    ]
