# Generated by Django 6.0.7 on 2026-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequirement',
            name='priority',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
