# Generated by Django 6.0.7 on 2026-09-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_lessonrequirement_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonrequirement',
            name='double_lessons_per_week',
            field=models.PositiveIntegerField(default=0, help_text='Number of double lessons required each week.'),
        ),
    ]
