# Generated by Django 6.0.7 on 2026-09-22 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0003_nssfrule_payerelief_payetaxband'),
        ('timetable', '0003_lessonrequirement_double_lessons_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablelesson',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timetablelesson',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether this lesson is visible to portal users.'),
        ),
        migrations.AddField(
            model_name='timetableteacher',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_teacher', to='hr_payroll.employee'),
        ),
        migrations.CreateModel(
            name='TimetableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='configuration', to='timetable.timetableterm')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableAssignmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('lessons_per_week', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(choices=[('SEPARATE', 'Separate Class'), ('JOINT', 'Joint Lesson')], default='SEPARATE', max_length=20)),
                ('duration', models.CharField(choices=[('SINGLE', 'Single Lesson'), ('DOUBLE', 'Double Lesson')], default='SINGLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_groups', to='timetable.timetableconfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=150)),
                ('exam_type', models.CharField(choices=[('CAT', 'CAT'), ('MIDTERM', 'Mid-Term'), ('ENDTERM', 'End-Term'), ('MOCK', 'Mock'), ('KJSEA', 'KJSEA'), ('KPSEA', 'KPSEA'), ('KCSE', 'KCSE'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='timetable.timetableclass')),
                ('invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='timetable.timetableteacher')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='timetable.timetableroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='timetable.timetablesubject')),
            ],
            options={
                'ordering': ['date', 'start_time', 'class_group__name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableTeacherSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('absent_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent_substitutions', to='timetable.timetableteacher')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='timetable.timetableclass')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='timetable.timetableday')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='timetable.timetableperiod')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='timetable.timetablesubject')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitute_assignments', to='timetable.timetableteacher')),
            ],
            options={
                'ordering': ['-date', 'period__order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='timetable.timetableterm')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='timetablelesson',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='timetable.timetableversion'),
        ),
        migrations.CreateModel(
            name='TimetableAssignmentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='timetable.timetableassignmentgroup')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_members', to='timetable.timetablesubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_members', to='timetable.timetableteacher')),
            ],
            options={
                'ordering': ['subject__name', 'teacher__name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'teacher', 'subject'), name='unique_timetable_app_assignment_member')],
            },
        ),
        migrations.CreateModel(
            name='TimetableConfiguredSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_number', models.PositiveIntegerField(default=1)),
                ('period_name', models.CharField(default='Period 1', max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('LESSON', 'Lesson'), ('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('GAMES', 'Games'), ('ACTIVITY', 'Activity'), ('ASSEMBLY', 'Assembly')], default='LESSON', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='timetable.timetableconfiguration')),
            ],
            options={
                'ordering': ['period_number', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('configuration', 'period_number'), name='unique_timetable_configured_slot')],
            },
        ),
        migrations.CreateModel(
            name='TimetableSlotRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_type', models.CharField(choices=[('LESSON', 'Lesson'), ('BREAK', 'Break'), ('LUNCH', 'Lunch'), ('GAMES', 'Games'), ('ACTIVITY', 'Activity'), ('ASSEMBLY', 'Assembly')], default='LESSON', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_rules', to='timetable.timetableday')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_rules', to='timetable.timetableperiod')),
            ],
            options={
                'ordering': ['day__order', 'period__order'],
                'constraints': [models.UniqueConstraint(fields=('day', 'period'), name='unique_timetable_app_slot_rule')],
            },
        ),
        migrations.CreateModel(
            name='TimetableTeacherClassAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100, null=True)),
                ('is_class_teacher', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_assignments', to='timetable.timetableteacher')),
            ],
            options={
                'ordering': ['teacher__name', 'class_name', 'stream'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'class_name', 'stream'), name='unique_timetable_teacher_class_assignment')],
            },
        ),
    ]
