# Generated by Django 6.0.7 on 2026-09-22 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_timetablelesson_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableTeacherTeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100)),
                ('lessons_per_week', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='timetable.timetablesubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='timetable.timetableteacher')),
            ],
            options={
                'ordering': ['class_name', 'stream', 'subject__name', 'teacher__name'],
            },
        ),
        migrations.CreateModel(
            name='TimetableTeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_links', to='timetable.timetablesubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subject_links', to='timetable.timetableteacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('teacher', 'subject'), name='unique_timetable_teacher_subject')],
            },
        ),
    ]
