# Generated by Django 6.0.7 on 2026-09-20 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('timetable', '0005_timetableteacherteachingassignment_and_more'),
        ('students', '0006_student_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('week_number', models.PositiveSmallIntegerField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=7)),
                ('teacher_report', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_reports_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_assessment_reports', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_assessment_reports', to='timetable.timetablesubject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_reports_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', 'student__last_name', 'student__first_name', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyReportReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_report_replies', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='weekly_reports.weeklyassessmentreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='weeklyassessmentreport',
            index=models.Index(fields=['student', 'week_start'], name='weekly_repo_student_5a127e_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyassessmentreport',
            index=models.Index(fields=['subject', 'week_start'], name='weekly_repo_subject_eb6361_idx'),
        ),
        migrations.AddIndex(
            model_name='weeklyassessmentreport',
            index=models.Index(fields=['class_name', 'week_start'], name='weekly_repo_class_n_717d11_idx'),
        ),
        migrations.AddConstraint(
            model_name='weeklyassessmentreport',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'week_start', 'week_end'), name='unique_student_subject_weekly_report'),
        ),
    ]

