# Generated by Django 6.0.7 on 2026-09-20 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0017_mpesapaybilltransaction'),
        ('weekly_reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAssessmentWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=100)),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_assessment_weeks', to='fees.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_assessment_weeks_created', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weekly_assessment_weeks_locked', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_assessment_weeks', to='fees.term')),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.AddField(
            model_name='weeklyassessmentreport',
            name='week',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='weekly_reports.weeklyassessmentweek'),
        ),
        migrations.AddConstraint(
            model_name='weeklyassessmentweek',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term', 'week_number'), name='unique_weekly_assessment_week'),
        ),
    ]
