# Generated by Django 6.0.7 on 2026-09-27 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_payroll', '0004_reset_payrollrecord_sequence'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['employee']},
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone',
        ),
        migrations.AddField(
            model_name='driver',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transport_driver', to='hr_payroll.employee'),
        ),
    ]
