# Generated by Django 6.0.7 on 2026-09-20 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0017_mpesapaybilltransaction'),
        ('timetable', '0005_timetableteacherteachingassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermlySubmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('stream', models.CharField(blank=True, max_length=100)),
                ('expected_schemes', models.PositiveIntegerField(default=0)),
                ('expected_records', models.PositiveIntegerField(default=0)),
                ('expected_lesson_plans', models.PositiveIntegerField(default=0)),
                ('admin_feedback', models.TextField(blank=True)),
                ('feedback_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termly_submission_requirements', to='fees.academicyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termly_submission_requirements', to='timetable.timetablesubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termly_submission_requirements', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='termly_submission_requirements', to='fees.term')),
            ],
            options={
                'ordering': ['class_name', 'stream', 'subject__name'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'academic_year', 'term', 'class_name', 'stream', 'subject'), name='unique_termly_submission_requirement')],
            },
        ),
    ]

