# Generated by Django 6.0.7 on 2026-09-20 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_timetableteacherteachingassignment_and_more'),
        ('termly_submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termlysubmissionrequirement',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termly_submission_requirements', to='timetable.timetableteacher'),
        ),
    ]

